### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [c-leri/Dynamic-Music#1]
Is this compatible with Ost Overhaul? 

It most likely isn't since they do the same thing and I'm not sure if these types of mods add to or replace the music in Minecraft, but I figured I'd ask before assuming.

**Comment by c-leri** [comment]
After a bit of testing it seems like the Ost Overhaul mod overides Dynamic Music.
I have honestly no idea how to fix that and after looking to the mod github page for answers it seems that the source code there isn't up to date with the mod's current version so...
