### ISSUE TITLE
The mod causes the game to crash on versions 1.19.2 and 1.19.4

### ISSUE THREAD

**Issue by Fleepe** [c-leri/Dynamic-Music#12]
1.19.2
[crash-2023-06-23_18.49.31-client.txt](https://github.com/c-leri/Dynamic-Music/files/11850042/crash-2023-06-23_18.49.31-client.txt)
[latest.log](https://github.com/c-leri/Dynamic-Music/files/11850043/latest.log)

1.19.4
[crash-2023-06-23_18.44.20-client.txt](https://github.com/c-leri/Dynamic-Music/files/11850014/crash-2023-06-23_18.44.20-client.txt)
[latest.log](https://github.com/c-leri/Dynamic-Music/files/11850017/latest.log)

Everything is updated: Windows 10 (22H2), Adoptium Java 8 (8.0.372.7) for 1.16.5 and 17 (17.0.7.7) for 1.19 and of course all mods are updated too.

**Comment by c-leri** [comment]
If you are using a config file from an earlier version of the mod you just need to change anything in the config selector part of the config then save and it should then fix itself!
