### ISSUE TITLE
Crash on loading world in Minecraft 1.20.1

### ISSUE THREAD

**Issue by PencilVoid** [c-leri/Dynamic-Music#13]
[Crash report](https://mclo.gs/YAIn3zk)
Minecraft 1.20.1
Quilt Loader 0.19.1

This happens consistently after loading a world but in one instance it happened after the Origins selection screen instead of before.

**Comment by c-leri** [comment]
This is because you are using the config file from the version 2.2.2 or earlier!

You need to go into the music selector part of the config and change anything then save so the config file can be regenerated will all the missing field from the newer versions
