### ISSUE TITLE
Change Music Delay

### ISSUE THREAD

**Issue by AmFerra** [c-leri/Dynamic-Music#14]
An option to change the delay between music? sometimes there is a large gap between tracks, and it would be nice to shorten or remove that.

**Comment by c-leri** [comment]
There are already many mods than do that and are compatible with Dynamic Music!

Two examples are [Music Duration Reducer](https://curseforge.com/minecraft/mc-mods/music-duration-reducer) and [Infinite Music](https://curseforge.com/minecraft/mc-mods/infinite-music)

It seems like they aren't updated to 1.20 though
