### ISSUE TITLE
Updated 1.16 Versions?

### ISSUE THREAD

**Issue by Spongecade** [c-leri/Dynamic-Music#18]
I was working on my own fork of Dynamic Music specifically for the 1.16 versions, having fixed some of the bugs relating to daytime, and called it [DynamicMusic-Legacy.](https://github.com/spongecade/DynamicMusic-Legacy) I was going to publish it as It's own mod but is there a chance we could collab on this fork and you could create two branches for my updated 1.16 versions?

**Comment by Spongecade** [comment]
If you want to make one 1.16 architectury branch you could do that too although I've never used the architectury api

**Comment by c-leri** [comment]
I"ll open a 1.16 architectury branch! Just make a pull request into it and I'll take care of architectury

**Comment by Spongecade** [comment]
Should I just push the actual src folders for the forge and fabric version and their respective build scripts?

**Comment by c-leri** [comment]
Oh you made two separate version !
Honestly maybe I should make 1.16.5-fabric and 1.16.5-forge branches then and keep theme separated

**Comment by Spongecade** [comment]
Thank you for that! I will be pushing the branches shortly!

**Comment by c-leri** [comment]
Just know that I won't be able to look at your pull request before a few days but I'll get back to it as soon as possible!

**Comment by Spongecade** [comment]
That's ok. Thanks for the response!
