### ISSUE TITLE
Can you change the music in any way, maybe with a resource pack?

### ISSUE THREAD

**Issue by svioletg** [c-leri/Dynamic-Music#2]
I couldn't seem to find anything saying how to change the music itself - is it hard-coded in, or is there some sort of configuration?

**Comment by c-leri** [comment]
All the musics are hard-coded in yes.
You could tinker with the code to add/remove any music you like by editing [this file](https://github.com/c-leri/Dynamic-Music/blob/1.19/src/main/resources/assets/dynmus/sounds.json)  and adding the new music files in [this directory](https://github.com/c-leri/Dynamic-Music/tree/1.19/src/main/resources/assets/dynmus/sounds/music).

**Comment by c-leri** [comment]
You can now tweak wich music plays when in the mod's config (it is still restricted to vanilla Minecraft music)
