### ISSUE TITLE
Boss Music incompatibility

### ISSUE THREAD

**Issue by Jukabofy** [c-leri/Dynamic-Music#4]
this mod doesn't let Cracker's Wither Strom boss theme to be played, maybe because of how this mod affects the music of minecraft

**Comment by c-leri** [comment]
Unfortunately Cracker's Wither Storm isn't open source and I can't look at how it handles the music to make Dynamic Music compatible with it, sorry :(

**Comment by Jukabofy** [comment]
Oh, I'll report this to Cracker's wither strom then
hope it helps for communication
