### ISSUE TITLE
Lisence Missing

### ISSUE THREAD

**Issue by FractalGeodes** [c-leri/Dynamic-Music#5]
Hi, was browsing Modrinth, and remembered that this is a fork, and I was slightly intrigued about if the license allowed for this. You've listed the mod on Modrinth and Curseforge as `LGPL-3.0-only`, same as the original, but the license is missing from the repository.

I went digging a bit, and found the license was removed [here](https://github.com/c-leri/Dynamic-Music/commit/e887bada14e7eba8c48989853e05c0ab7b9c1657#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7)

I'm assuming based on the licenses on the mod pages that this was accidental, but just wanted to bring your attention to it before it causes any more trouble than needs to happen.

**Comment by c-leri** [comment]
Ah yes sorry, I am unfamiliar with legal issues and I simply forgot to add it back when I changed the mod template, thank you!
Also I did ask the original creator of the mod for their permission when publishing the fork so they probably won't sue me
