### ISSUE TITLE
Bug with Creative mode

### ISSUE THREAD

**Issue by Quahami** [c-leri/Dynamic-Music#7]
- 1.19.2 2.2.2, fabric
In the end, all ambience music is "skipped" when i landing or taking off from ground in creative mode flying. This is not a problem with the keyboard or some stuff in minecraft control settings, I checked the double-click on the spacebar in the surviving mode, bug disappears. Deleting other mods doesn't help, deleting resource packs doesn't help, I just don't understand how to fix it, help pls. -_-'

**Comment by c-leri** [comment]
This was a bug related  to how I checked if the player was in creative mode!
It should be fixed in the 2.3 version, please tell me if you encounter this bug again.
