### ISSUE TITLE
Music selector not working correctly

### ISSUE THREAD

**Issue by 69ShadesOfPeanut** [c-leri/Dynamic-Music#8]
Using fabric 1.19.3, 2.2.2

I have selected all the new songs to be disabled via the music selector, I also have "cold" and "hot" music disabled so its just cave, nice, and down. However the songs that play are the default config of the mod. I do have the "infinite music" mod installed that just lessens the time between tracks playing if that somehow has any impact on the behaviour of Dynamic Music

**Comment by c-leri** [comment]
This should be fixed in the 2.3 version! Please tell me if you encounter this bug again.
